remember ndim

In [1]:
import numpy as np
a=np.array([1,2,3])
a.ndim


1

In [3]:

a=np.array([[1,2,3],[5,67,43]])
a.ndim


2

remember itemsize

In [6]:

a=np.array([1,2,3])
a.itemsize


4

dtype

In [7]:

a=np.array([1,2,3])
a.dtype


dtype('int32')

change to float

In [9]:

a=np.array([1,2,3],dtype=np.float64)
a.dtype


dtype('float64')

size
it gives size of the array

In [3]:

a=np.array([1,2,3],dtype=np.float64)
a.size


3

complex numbers

In [7]:

a=np.array([[5,2],[5,6]] ,dtype=complex)
a

array([[5.+0.j, 2.+0.j],
       [5.+0.j, 6.+0.j]])

zeroes and ones array

In [22]:

np.zeros((5,5))
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#range function in numpy
arange

In [21]:

a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

linspace it will divide array into linearly
let see an example

In [20]:
a=np.linspace(0,100,100)
a

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63