# numpy

#ndim

In [94]:
import numpy as np
a=np.array([1,2,3])
a.ndim


1

In [95]:

a=np.array([[1,2,3],[5,67,43]])
a.ndim


2

#itemsize

In [96]:

a=np.array([1,2,3])
a.itemsize


4

#dtype

In [97]:

a=np.array([1,2,3])
a.dtype


dtype('int32')

#change to float

In [98]:

a=np.array([1,2,3],dtype=np.float64)
a.dtype


dtype('float64')

#size
it gives size of the array

In [99]:

a=np.array([1,2,3],dtype=np.float64)
a.size


3

#complex numbers

In [100]:

a=np.array([[5,2],[5,6]] ,dtype=complex)
a

array([[5.+0.j, 2.+0.j],
       [5.+0.j, 6.+0.j]])

#zeroes and ones array

In [101]:

np.zeros((5,5))
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

#range function in numpy
arange

In [102]:

a=np.arange(100)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

#linspace
linspace it will divide array into linearly
let see an example

In [103]:
a=np.linspace(0,100,100)
a

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

#reshape fuction

In [104]:
a.reshape(50,2)

array([[  0.        ,   1.01010101],
       [  2.02020202,   3.03030303],
       [  4.04040404,   5.05050505],
       [  6.06060606,   7.07070707],
       [  8.08080808,   9.09090909],
       [ 10.1010101 ,  11.11111111],
       [ 12.12121212,  13.13131313],
       [ 14.14141414,  15.15151515],
       [ 16.16161616,  17.17171717],
       [ 18.18181818,  19.19191919],
       [ 20.2020202 ,  21.21212121],
       [ 22.22222222,  23.23232323],
       [ 24.24242424,  25.25252525],
       [ 26.26262626,  27.27272727],
       [ 28.28282828,  29.29292929],
       [ 30.3030303 ,  31.31313131],
       [ 32.32323232,  33.33333333],
       [ 34.34343434,  35.35353535],
       [ 36.36363636,  37.37373737],
       [ 38.38383838,  39.39393939],
       [ 40.4040404 ,  41.41414141],
       [ 42.42424242,  43.43434343],
       [ 44.44444444,  45.45454545],
       [ 46.46464646,  47.47474747],
       [ 48.48484848,  49.49494949],
       [ 50.50505051,  51.51515152],
       [ 52.52525253,  53.53535354],
 

In [105]:
a
#but it doesn't touch the orginal function

array([  0.        ,   1.01010101,   2.02020202,   3.03030303,
         4.04040404,   5.05050505,   6.06060606,   7.07070707,
         8.08080808,   9.09090909,  10.1010101 ,  11.11111111,
        12.12121212,  13.13131313,  14.14141414,  15.15151515,
        16.16161616,  17.17171717,  18.18181818,  19.19191919,
        20.2020202 ,  21.21212121,  22.22222222,  23.23232323,
        24.24242424,  25.25252525,  26.26262626,  27.27272727,
        28.28282828,  29.29292929,  30.3030303 ,  31.31313131,
        32.32323232,  33.33333333,  34.34343434,  35.35353535,
        36.36363636,  37.37373737,  38.38383838,  39.39393939,
        40.4040404 ,  41.41414141,  42.42424242,  43.43434343,
        44.44444444,  45.45454545,  46.46464646,  47.47474747,
        48.48484848,  49.49494949,  50.50505051,  51.51515152,
        52.52525253,  53.53535354,  54.54545455,  55.55555556,
        56.56565657,  57.57575758,  58.58585859,  59.5959596 ,
        60.60606061,  61.61616162,  62.62626263,  63.63

#ravel
ravel it will flat the array
see example

In [106]:
a=np.array([[1,2,3], [4,5,6]])
print(a.ravel())
a


[1 2 3 4 5 6]


array([[1, 2, 3],
       [4, 5, 6]])

some normally used functions
standard deviation also there

In [107]:
print(a)
print(a.min())
print(a.max())
print(a.sum())
# it has axis 
"""
Actually axis=0 represent colu
and axis=1 represent row
"""
print(a.sum(axis=0))
print(a.sum(axis=1))
a.std()

[[1 2 3]
 [4 5 6]]
1
6
21
[5 7 9]
[ 6 15]


1.707825127659933

#matrix functions

In [108]:
b=np.array([[7,8,9],[10,11,12],[13,14,15]])
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a.dot(b))
print("\n",a+b)

print("\n",a-b)
print("\n",a*b)
print("\n",a/b)

[[ 66  72  78]
 [156 171 186]
 [246 270 294]]

 [[ 8 10 12]
 [14 16 18]
 [20 22 24]]

 [[-6 -6 -6]
 [-6 -6 -6]
 [-6 -6 -6]]

 [[  7  16  27]
 [ 40  55  72]
 [ 91 112 135]]

 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]
 [0.53846154 0.57142857 0.6       ]]


# SLICING/INDEXING

In [126]:
s=np.array([[1,2,3], [4,5,6], [7,8,9]])
print(s[-1])
print(s[0:3,2])#accessing column
print(s[1,0:2])#accessing row

[7 8 9]
[3 6 9]
[4 5]


In [128]:
#it will access the row
for i in s:
    print(i)


[1 2 3]
[4 5 6]
[7 8 9]


flat is a keyword it will flat the array

In [129]:
for i in s.flat:
    print(i)

1
2
3
4
5
6
7
8
9


# stacking array

In [172]:
a=np.arange(16).reshape(4,4)
b=np.arange(16,32).reshape(4,4)
print(a,"\n","\n",b)
print(np.hstack((a,b)))
print("\n",np.vstack((a,b)))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 
 
 [[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[ 0  1  2  3 16 17 18 19]
 [ 4  5  6  7 20 21 22 23]
 [ 8  9 10 11 24 25 26 27]
 [12 13 14 15 28 29 30 31]]

 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


 # spliting

In [162]:
print(np.split(a,4))

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]]), array([[12, 13, 14, 15]])]


In [ ]:
# indexing  boolean

In [173]:
print(b)
c=b>20
print(c)
k=b[c]
print(k)


[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]
[21 22 23 24 25 26 27 28 29 30 31]


#iteration in numpy
nditer

In [189]:
a=np.arange(0,32,2).reshape(4,4)
print(a)
# c for row and F column Forten Order
for i in np.nditer(a,order="c"):
    print(i)
print("Forten Order")
for i in np.nditer(a,order="F"):
    print(i)
# if want a loop u can use flags as "external_loop"  
for i in np.nditer(a,order="f",flags=["external_loop"]):
    print(i)
for i in np.nditer(a,order="c",flags=["external_loop"] ):
    print(i) 

[[ 0  2  4  6]
 [ 8 10 12 14]
 [16 18 20 22]
 [24 26 28 30]]
0
2
4
6
8
10
12
14
16
18
20
22
24
26
28
30
Forten Order
0
8
16
24
2
10
18
26
4
12
20
28
6
14
22
30
[ 0  8 16 24]
[ 2 10 18 26]
[ 4 12 20 28]
[ 6 14 22 30]
[ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28 30]


op_flags

In [195]:
for x in np.nditer(a,op_flags=["readwrite"]):
    x=x*x
a
    


array([[  0,   4,  16,  36],
       [ 64, 100, 144, 196],
       [256, 324, 400, 484],
       [576, 676, 784, 900]])